const _favouriteDietAttributes = [
  "fm_uuid",
  "fm_name",
  "fm_code",
  "fm_dept",
  "fm_userid",
  "fm_favourite_type_uuid",
  "fm_active",
  "fm_public",
  "fm_status",
  "fm_display_order",
  "fmd_diet_master_uuid",
  "fmd_diet_frequency_uuid",
  "fmd_diet_category_uuid",
  "fmd_quantity",
  "dm_code",
  "dm_name",
  "df_code",
  "df_name",
  "dc_code",
  "dc_name",
  "uct_name",
  "uc_first_name",
  "uc_middle_name",
  "uc_last_name",
  "umt_name",
  "um_first_name",
  "um_middle_name",
  "um_last_name",
  "fa_uuid",
  "fa_name",
  "dp_uuid",
  "dp_name",
  "dm_status",
  "dm_is_active",
  "fm_created_date",
  "fm_modified_date",
  "fm_description"
];

module.exports = {
  favouriteDietAttributes: _favouriteDietAttributes
};
